trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude: 
    - README.md
    - LICENSE
    include:
    - app

#How to Build and Deploy Docker Containers with Azure Pipelines
#https://www.youtube.com/watch?v=272GOWKDqP4

pool:
  vmImage: ubuntu-latest

stages:
  - stage: dev
    jobs:
    - job: Build
      steps:

      - task: Docker@2
        inputs:
          containerRegistry: 'AzureACR'
          repository: 'nodejs-app'
          command: 'buildAndPush'
          Dockerfile: '$(System.DefaultWorkingDirectory)/app/Dockerfile' #'$(System.DefaultWorkingDirectory)/${{ parameters.work_dir }}'
          tags: 'latest'

      # # Build container image
      # - task: Docker@1
      #   displayName: 'Build container image'
      #   inputs:
      #     azureSubscriptionEndpoint: 'AzureSC'
      #     azureContainerRegistry: '$(acrHostName)'
      #     imageName: '$(imageName):$(Build.BuildId)'
      #     useDefaultContext: false
      #     buildContext: '$(System.DefaultWorkingDirectory)/PublishedWebApp'
      
      # # Push container image
      # - task: Docker@1
      #   displayName: 'Push container image'
      #   inputs:
      #     azureSubscriptionEndpoint: 'AzureSC'
      #     azureContainerRegistry: '$(acrHostName)'
      #     command: 'Push an image'
      #     imageName: '$(imageName):$(Build.BuildId)'
