trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude: 
    - README.md
    - LICENSE
    include:
    - app

parameters:
  - name: containerRegistry
    default: "AzureACR"

pool:
  vmImage: ubuntu-latest

stages:
  - stage: dev
    jobs:
    - job: Build
      steps:

      - task: Docker@2
        inputs:
          containerRegistry: ${{ parameters.containerRegistry }}
          repository: 'nodejs-app'
          command: 'buildAndPush'
          Dockerfile: '$(System.DefaultWorkingDirectory)/app/Dockerfile'
          tags: 'latest'
