trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude: 
    - README.md
    - LICENSE
    include:
    - terraform-main

#How to Build and Deploy Docker Containers with Azure Pipelines
#https://www.youtube.com/watch?v=272GOWKDqP4

pool:
  vmImage: ubuntu-latest

stages:
  - stage: dev
    jobs:
    - job: Build
      steps:
