parameters:
  - name: include_root_rolder
  - name: work_dir
  - name : archive_type
  - name: output_file

jobs:
  - job: 'ArchiveFile'
    pool:
      vmImage: ubuntu-latest

    steps:
      - task: ArchiveFiles@2
        inputs:
          includeRootFolder: ${{ parameters.include_root_rolder }}
          rootFolderOrFile: ${{ parameters.work_dir }}
          archiveType: ${{ parameters.archive_type }}
          archiveFile: ${{ parameters.output_file }}.${{ parameters.archive_type }}