parameters:
  - name: include_root_rolder
  - name: work_dir
  - name : archive_type
  - name: output_file
  - name: depends_on
    default: []

jobs:
  - job: 'ArchiveFile'
    dependsOn: ${{ parameters.depends_on }}
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: ArchiveFiles@2
        inputs:
          includeRootFolder: ${{ parameters.include_root_rolder }}
          rootFolderOrFile: ${{ parameters.work_dir }}
          archiveType: ${{ parameters.archive_type }}
          archiveFile: ${{ parameters.output_file }}.${{ parameters.archive_type }}

      - task: DownloadPipelineArtifact@2
        inputs:
          inputs:
            artifact: drop

      - task: CmdLine@2 
        displayName: "Check LS"
        inputs:
          script: 'ls -ltr'

      - task: CmdLine@2 
        displayName: "Check LS"
        inputs:
          script: 'ls -ltr $(System.ArtifactsDirectory)/'