parameters:
  - name: input_file
  - name: output_file
  - name: file_name
  - name: file_destination

jobs:
  - job: 'Terraform'
    pool:
      vmImage: ubuntu-latest

    steps:
      - task: CmdLine@2 
        displayName: "Save file into Storage Account"
        inputs:
          inlineScript: |
            $ReadOutputFile = Get-Content ${{ parameters.input_file }} | Out-String | ConvertFrom-Json
            az storage blob upload --account-name $ReadOutputFile.storage_account_name --container-name $ReadOutputFile.storage_container_name --name ${{ parameters.file_name }} --file ${{ parameters.file_location }}