parameters:
  - name: artifact_name
  - name: output_file
  - name: file_name
  - name: depends_on
    default: []

jobs:
  - job: 'SaveFile'
    dependsOn: ${{ parameters.depends_on }}
    pool:
      vmImage: ubuntu-latest

    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: ${{ parameters.artifact_name }}
          downloadPath: '$(System.ArtifactsDirectory)'
          
      - task: AzureCLI@2
        retryCountOnTaskFailure: 2
        inputs:
          workingDirectory: '$(System.ArtifactsDirectory)/${{ parameters.artifact_name }}'
          azureSubscription: 'AzureDevOps'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            $json = Get-Content '${{ parameters.file_name }}' | Out-String | ConvertFrom-Json
            $storage_account_name = $json.storage_account_name.value
            $storage_container_name = $json.storage_container_name.value
            az storage blob upload --account-name $storage_account_name --container-name $storage_container_name --name ${{ parameters.output_file }} --file ${{ parameters.output_file }} --auth-mode key