parameters:
  - name: input_file
  - name: output_file
  - name: file_name
  - name: file_destination
  - name: depends_on
    default: []

jobs:
  - job: 'SaveFile'
    dependsOn: ${{ parameters.depends_on }}
    pool:
      vmImage: ubuntu-latest

    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'drop'
          downloadPath: '$(System.ArtifactsDirectory)'

      # - task: CmdLine@2 
      #   displayName: "Save file into Storage Account"
      #   inputs:
      #     inlineScript: |
      #       $ReadOutputFile = Get-Content ${{ parameters.input_file }} | Out-String | ConvertFrom-Json
      #       az storage blob upload --account-name $ReadOutputFile.storage_account_name --container-name $ReadOutputFile.storage_container_name --name ${{ parameters.file_name }} --file ${{ parameters.file_location }}