parameters:
  - name: backendDir
    default: "terraform-backend"
  - name: app_name
    default: "nodejs-docker-backend"

variables:
  - group: "nodejs-mysql-docker-group"

pool:
  vmImage: ubuntu-latest

stages:
  - stage: dev
    jobs:
    - template: ../templates/terraform.yml
      parameters:
        terraform_work_dir: ${{ parameters.backendDir }}
        app_name: ${{ parameters.app_name }}
